package org.acme.restclient;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private java.lang.String institutionName;
    private java.lang.String officerName;
    private java.lang.String institutionAddress;
    private java.lang.String entityTypes;
    private java.lang.String charitableStatus;
    private Integer size;
    private java.lang.String industryType;
    private Float totalAssets;
    private String registrationCountry;

    public Float getTotalAssets() {
        return totalAssets;
    }

    public void setTotalAssets(Float totalAssets) {
        this.totalAssets = totalAssets;
    }

    public String getRegistrationCountry() {
        return registrationCountry;
    }

    public void setRegistrationCountry(String registrationCountry) {
        this.registrationCountry = registrationCountry;
    }

    public Customer() {
    }

    public java.lang.String getInstitutionName() {
        return this.institutionName;
    }

    public void setInstitutionName(java.lang.String institutionName) {
        this.institutionName = institutionName;
    }

    public java.lang.String getOfficerName() {
        return this.officerName;
    }

    public void setOfficerName(java.lang.String officerName) {
        this.officerName = officerName;
    }

    public java.lang.String getInstitutionAddress() {
        return this.institutionAddress;
    }

    public void setInstitutionAddress(java.lang.String institutionAddress) {
        this.institutionAddress = institutionAddress;
    }

    public java.lang.String getEntityTypes() {
        return this.entityTypes;
    }

    public void setEntityTypes(java.lang.String entityTypes) {
        this.entityTypes = entityTypes;
    }

    public java.lang.String getCharitableStatus() {
        return this.charitableStatus;
    }

    public void setCharitableStatus(java.lang.String charitableStatus) {
        this.charitableStatus = charitableStatus;
    }

    public java.lang.String getIndustryType() {
        return this.industryType;
    }

    public void setIndustryType(java.lang.String industryType) {
        this.industryType = industryType;
    }

    public String toString() {
        return this.institutionName + "::" + this.officerName + "::"
                + this.institutionAddress + "::" + this.entityTypes + "::"
                + this.charitableStatus + "::" + this.size + "::"
                + this.industryType;
    }

    public java.lang.Integer getSize() {
        return this.size;
    }

    public void setSize(java.lang.Integer size) {
        this.size = size;
    }

    public Customer(java.lang.String institutionName,
                    java.lang.String officerName, java.lang.String institutionAddress,
                    java.lang.String entityTypes, java.lang.String charitableStatus,
                    java.lang.Integer size, java.lang.String industryType) {
        this.institutionName = institutionName;
        this.officerName = officerName;
        this.institutionAddress = institutionAddress;
        this.entityTypes = entityTypes;
        this.charitableStatus = charitableStatus;
        this.size = size;
        this.industryType = industryType;
    }

}